#!/usr/bin/bash

# Policy Authentication Agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export $(gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)

# https://wiki.hyprland.org/FAQ/#some-of-my-apps-take-a-really-long-time-to-open
# https://gist.github.com/PowerBall253/2dea6ddf6974ba4e5d26c3139ffb7580
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP --all &

export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/gcr/ssh

# variables
scripts=~/.scripts

# gsettings
#gsettings set org.gnome.desktop.interface gtk-theme 'Tokyonight-Dark-BL-LB'
gsettings set org.gnome.desktop.interface font-name 'Hack Nerd Font 9'
#gsettings set org.gnome.desktop.interface icon-theme 'Tokyonight-Moon'
gsettings set org.gnome.desktop.interface cursor-theme 'Sweet-cursors'

#QT Settings
export QT_QPA_PLATFORMTHEME=gtk2

# Hyprland Plugin Manager
#hyprpm reload -n
# notification daemon
swaync &

# hypride
hypridle &

# waybar
$scripts/launch_waybar &

# wallpaper
$scripts/wall ~/.config/hypr/wallpapers/current_wallpaper.png &

# Applets
# $scripts/appindicator.py &
blueman-applet &
nm-applet --indicator &\

# Startup Applications
#spotify-launcher &
#Discord &
#thunderbird &
# Moving startup apps to 2nd workspace
hyprctl dispatch exec [workspace 2 silent] spotify-launcher
hyprctl dispatch exec [workspace 2 silent] discord
hyprctl dispatch exec [workspace 2 silent] thunderbird


# other
hyprctl setcursor Sweet-cursors 24
wl-paste --watch cliphist store &
notify-send -a aurora "Hello $(whoami)!" &
libinput-gestures-setup start &

sleep 1
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal
/usr/lib/xdg-desktop-portal-hyprland &
sleep 2
/usr/lib/xdg-desktop-portal &
